name: Check and Deploy Docker App

on:
  push:
    branches:
      - main

jobs:
  check-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if index.html exists
        run: |
          if [ ! -f index.html ]; then
            echo "index.html not found!"
            exit 1
          fi

  build-and-push:
    needs: check-file
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: patheex117/cloud-web:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull patheex117/cloud-web:latest

            OLD_BY_PORT=$(sudo docker ps -q --filter "publish=8080")
            if [ -n "$OLD_BY_PORT" ]; then
              sudo docker stop $OLD_BY_PORT || true
              sudo docker rm $OLD_BY_PORT || true
            fi

            sudo docker stop cloud-web || true
            sudo docker rm cloud-web || true

            sudo docker run -d --name cloud-web -p 8080:80 patheex117/cloud-web:latest
