name: Check index file

on: [push]

jobs:
  check-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if index.html exists
        run: |
          if [ ! -f index.html ]; then
            echo "index.html not found!"
            exit 1
          fi


  deploy:
    needs: check-file
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/cloud-web
            git pull
